// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/billykore/kore/backend/pkg/config"
	"github.com/billykore/kore/backend/pkg/db"
	"github.com/billykore/kore/backend/pkg/log"
	"github.com/billykore/kore/backend/services/todo/internal/handler"
	"github.com/billykore/kore/backend/services/todo/internal/repo"
	"github.com/billykore/kore/backend/services/todo/internal/server"
	"github.com/billykore/kore/backend/services/todo/internal/usecase"
)

import (
	_ "github.com/joho/godotenv/autoload"
)

// Injectors from wire.go:

func todoApp(cfg *config.Config) *app {
	logger := log.NewLogger()
	gormDB := db.NewPostgres(cfg)
	todoRepo := repo.NewTodoRepository(gormDB)
	todoUsecase := usecase.NewTodoUsecase(logger, todoRepo)
	todoHandler := handler.NewTodoHandler(todoUsecase)
	httpServer := server.SetupHTTPServer(cfg, logger, todoHandler)
	mainApp := newApp(httpServer)
	return mainApp
}
