services:
  otp-db-postgres:
    image: postgres:alpine3.19
    container_name: otp-db-postgres
    env_file:
      - db.env
    ports:
      - "9003:5432"
    volumes:
      - otp-db-postgres-volume:/var/lib/postgresql/data
    networks:
      - backend-net

  otp-service:
    container_name: otp-service
    image: billykore/otp-service:latest
    ports:
      - "3003:8000"
    env_file:
      - service.env
    depends_on:
      - otp-db-postgres
    networks:
      - backend-net

volumes:
  otp-db-postgres-volume:
    name: otp-db-postgres-volume
    external: true

networks:
  backend-net:
    name: backend-net
    external: true
