// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/billykore/kore/backend/pkg/broker/rabbit"
	"github.com/billykore/kore/backend/pkg/config"
	"github.com/billykore/kore/backend/pkg/db"
	"github.com/billykore/kore/backend/pkg/log"
	"github.com/billykore/kore/backend/services/order/handler"
	"github.com/billykore/kore/backend/services/order/repo"
	"github.com/billykore/kore/backend/services/order/server"
	"github.com/billykore/kore/backend/services/order/usecase"
	"github.com/labstack/echo/v4"
)

import (
	_ "github.com/joho/godotenv/autoload"
)

// Injectors from wire.go:

func orderApp(cfg *config.Config) *app {
	logger := log.NewLogger()
	echoEcho := echo.New()
	gormDB := db.NewPostgres(cfg)
	orderRepository := repo.NewPaymentRepository(gormDB)
	orderUsecase := usecase.NewOrderUsecase(logger, orderRepository)
	rabbitRabbit := rabbit.New(cfg, logger)
	orderHandler := handler.NewOrderHandler(orderUsecase, rabbitRabbit)
	router := server.NewRouter(cfg, logger, echoEcho, orderHandler)
	httpServer := server.NewHTTPServer(router)
	brokerServer := server.NewBrokerServer(logger, orderHandler)
	mainApp := newApp(httpServer, brokerServer)
	return mainApp
}
