// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/billykore/kore/libs/config"
	"github.com/billykore/kore/libs/pkg/log"
	"github.com/billykore/kore/services/user/repository"
	"github.com/billykore/kore/services/user/server"
	"github.com/billykore/kore/services/user/service"
	"github.com/billykore/kore/services/user/usecase"
)

import (
	_ "github.com/joho/godotenv/autoload"
)

// Injectors from wire.go:

func userApp(cfg *config.Config) *app {
	logger := log.NewLogger()
	greeter := repository.NewGreetRepository()
	greetUsecase := usecase.NewGreetUsecase(logger, greeter)
	userService := service.NewUserService(greetUsecase)
	httpServer := server.NewHTTPServer(logger, cfg, userService)
	grpcServer := server.NewGRPCServer(logger, cfg, userService)
	mainApp := newApp(httpServer, grpcServer)
	return mainApp
}
