// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/billykore/kore/libs/config"
	"github.com/billykore/kore/libs/pkg/log"
	"github.com/billykore/kore/services/book/repo"
	"github.com/billykore/kore/services/book/server"
	"github.com/billykore/kore/services/book/service"
	"github.com/billykore/kore/services/book/usecase"
	"github.com/labstack/echo/v4"
)

import (
	_ "github.com/joho/godotenv/autoload"
)

// Injectors from wire.go:

func bookApp(cfg *config.Config) *app {
	logger := log.NewLogger()
	echoEcho := echo.New()
	greeterRepository := repo.NewBookRepository()
	bookUsecase := usecase.NewBookUsecase(logger, greeterRepository)
	bookService := service.NewBookService(bookUsecase)
	router := server.NewRouter(cfg, logger, echoEcho, bookService)
	httpServer := server.NewHTTPServer(router)
	mainApp := newApp(httpServer)
	return mainApp
}
