### get todos
GET http://localhost:8080/todos
Content-Type: application/json
Accept: application/json

### get done todos
GET http://localhost:8080/todos?isDone=true
Content-Type: application/json
Accept: application/json

### get not done todos
GET http://localhost:8080/todos?isDone=false
Content-Type: application/json
Accept: application/json

### get todo by id
GET http://localhost:8080/todos/5b9c7f66-9fbc-11ee-99cb-ee85fce9a206
Content-Type: application/json
Accept: application/json

### save todo
POST http://localhost:8080/todos
Content-Type: application/json
Accept: application/json

{
  "title": "Test",
  "description": "Test description."
}

### set done todo
PUT http://localhost:8080/todos/5b9c7f66-9fbc-11ee-99cb-ee85fce9a206
Content-Type: application/json
Accept: application/json

{
  "isDone": true
}

### delete todo
DELETE http://localhost:8080/todos/5b9c7f66-9fbc-11ee-99cb-ee85fce9a206
Content-Type: application/json
Accept: application/json
