// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/billykore/kore/backend/internal/domain/order"
	"github.com/billykore/kore/backend/internal/domain/otp"
	"github.com/billykore/kore/backend/internal/domain/product"
	"github.com/billykore/kore/backend/internal/domain/shipping"
	"github.com/billykore/kore/backend/internal/domain/user"
	"github.com/billykore/kore/backend/internal/infra/db/postgres"
	"github.com/billykore/kore/backend/internal/infra/db/repository"
	"github.com/billykore/kore/backend/internal/infra/email/brevo"
	"github.com/billykore/kore/backend/internal/infra/email/mailer"
	"github.com/billykore/kore/backend/internal/infra/http/handler"
	"github.com/billykore/kore/backend/internal/infra/http/server"
	"github.com/billykore/kore/backend/internal/infra/messaging"
	"github.com/billykore/kore/backend/internal/infra/messaging/consumer"
	"github.com/billykore/kore/backend/internal/infra/messaging/producer"
	"github.com/billykore/kore/backend/internal/infra/messaging/rabbitmq"
	"github.com/billykore/kore/backend/pkg/config"
	"github.com/billykore/kore/backend/pkg/logger"
	"github.com/billykore/kore/backend/pkg/validation"
	"github.com/labstack/echo/v4"
)

import (
	_ "github.com/joho/godotenv/autoload"
)

// Injectors from wire.go:

func initApp(cfg *config.Config) *app {
	loggerLogger := logger.New()
	echoEcho := echo.New()
	db := postgres.New(cfg)
	userRepository := repository.NewUserRepository(db)
	service := user.NewService(loggerLogger, userRepository)
	userHandler := handler.NewUserHandler(service)
	orderRepository := repository.NewOrderRepository(db)
	orderService := order.NewService(loggerLogger, orderRepository)
	connection := rabbitmq.NewConnection(cfg)
	orderHandler := handler.NewOrderHandler(orderService, connection)
	otpRepository := repository.NewOtpRepository(db)
	client := brevo.NewClient(cfg)
	otpEmail := mailer.NewOTPEmail(loggerLogger, client)
	otpService := otp.NewService(loggerLogger, otpRepository, otpEmail)
	validator := validation.New()
	otpHandler := handler.NewOtpHandler(otpService, validator)
	productRepository := repository.NewProductRepository(db)
	productService := product.NewService(loggerLogger, productRepository)
	productHandler := handler.NewProductHandler(productService)
	shippingRepository := repository.NewShippingRepository(db)
	shippingProducer := producer.NewShippingProducer(cfg, loggerLogger, connection)
	shippingService := shipping.NewService(loggerLogger, shippingRepository, shippingProducer)
	shippingHandler := handler.NewShippingHandler(shippingService)
	router := server.NewRouter(cfg, loggerLogger, echoEcho, userHandler, orderHandler, otpHandler, productHandler, shippingHandler)
	serverServer := server.New(router)
	orderConsumer := consumer.NewOrderConsumer(cfg, loggerLogger, orderService, connection)
	messagingConsumer := messaging.NewConsumer(cfg, loggerLogger, orderConsumer)
	mainApp := newApp(serverServer, messagingConsumer)
	return mainApp
}
