// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/billykore/kore/backend/internal/app/order"
	"github.com/billykore/kore/backend/internal/app/otp"
	"github.com/billykore/kore/backend/internal/app/product"
	"github.com/billykore/kore/backend/internal/app/shipping"
	"github.com/billykore/kore/backend/internal/app/user"
	"github.com/billykore/kore/backend/internal/infra/database/postgres"
	"github.com/billykore/kore/backend/internal/infra/http"
	"github.com/billykore/kore/backend/internal/infra/http/handler"
	"github.com/billykore/kore/backend/internal/infra/mail"
	"github.com/billykore/kore/backend/internal/infra/messaging/rabbit"
	"github.com/billykore/kore/backend/internal/infra/persistence"
	"github.com/billykore/kore/backend/pkg/config"
	"github.com/billykore/kore/backend/pkg/logger"
	"github.com/billykore/kore/backend/pkg/validation"
	"github.com/labstack/echo/v4"
)

import (
	_ "github.com/joho/godotenv/autoload"
)

// Injectors from wire.go:

func initKore(cfg *config.Config) *kore {
	loggerLogger := logger.New()
	echoEcho := echo.New()
	db := persistence.NewPostgres(cfg)
	userRepository := postgres.NewUserRepository(db)
	service := user.NewService(loggerLogger, userRepository)
	userHandler := handler.NewUserHandler(service)
	orderRepository := postgres.NewOrderRepository(db)
	orderService := order.NewService(loggerLogger, orderRepository)
	rabbitRabbit := rabbit.New(cfg, loggerLogger)
	orderHandler := handler.NewOrderHandler(orderService, rabbitRabbit)
	otpRepository := postgres.NewOtpRepository(db)
	mailer := mail.NewSender(cfg)
	otpService := otp.NewService(loggerLogger, otpRepository, mailer)
	validator := validation.New()
	otpHandler := handler.NewOtpHandler(otpService, validator)
	productRepository := postgres.NewProductRepository(db)
	productService := product.NewService(loggerLogger, productRepository)
	productHandler := handler.NewProductHandler(productService)
	shippingRepository := postgres.NewShippingRepository(db)
	shippingService := shipping.NewService(loggerLogger, rabbitRabbit, shippingRepository)
	shippingHandler := handler.NewShippingHandler(shippingService)
	router := http.NewRouter(cfg, loggerLogger, echoEcho, userHandler, orderHandler, otpHandler, productHandler, shippingHandler)
	server := http.NewServer(router)
	mainKore := newKore(server)
	return mainKore
}
