apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: todo-service
  template:
    metadata:
      name: todo-service
      labels:
        name: todo-service
    spec:
      containers:
        - name: todo-app
          image: billykore/todo-service:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: todo-service-env
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 300m
              memory: 300Mi
      restartPolicy: Always
      automountServiceAccountToken: false

---

apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  selector:
    name: todo-service
  ports:
    - name: "http"
      port: 8000
      targetPort: 8000
  type: ClusterIP
