apiVersion: apps/v1
kind: Deployment
metadata:
  name: otp-db-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otp-db-postgres
  template:
    metadata:
      labels:
        app: otp-db-postgres
    spec:
      containers:
        - name: otp-db-postgres
          image: postgres:alpine3.19
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: otp-db-postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: otp-db-postgres-data
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
              ephemeral-storage: 1Gi
            limits:
              cpu: 300m
              memory: 300Mi
              ephemeral-storage: 1Gi
      volumes:
        - name: otp-db-postgres-data
          persistentVolumeClaim:
            claimName: otp-db-postgres-volume-claim
      automountServiceAccountToken: false

---

apiVersion: v1
kind: Service
metadata:
  name: otp-db-postgres
  labels:
    app: otp-db-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: otp-db-postgres
