// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/billykore/kore/libs/config"
	"github.com/billykore/kore/libs/database/firestore"
	"github.com/billykore/kore/libs/pkg/log"
	"github.com/billykore/kore/services/auth/repository"
	"github.com/billykore/kore/services/auth/server"
	"github.com/billykore/kore/services/auth/service"
	"github.com/billykore/kore/services/auth/usecase"
)

import (
	_ "github.com/joho/godotenv/autoload"
)

// Injectors from wire.go:

func authApp(cfg *config.Config) *app {
	logger := log.NewLogger()
	client := firestore.New(cfg)
	user := repository.NewUserRepository(client)
	authUsecase := usecase.NewAuthUsecase(logger, user)
	authService := service.NewAuthService(authUsecase)
	httpServer := server.NewHTTPServer(logger, cfg, authService)
	grpcServer := server.NewGRPCServer(logger, cfg, authService)
	mainApp := newApp(httpServer, grpcServer)
	return mainApp
}
