apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list-app
  labels:
    name: todo-list-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: todo-list-app-service
  template:
    metadata:
      name: todo-list-app-service
      labels:
        name: todo-list-app-service
    spec:
      containers:
        - name: todo-list-app
          image: billykore/todo-list-app:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: todo-list-app-env
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 300m
              memory: 300Mi
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: todo-list-app-service
spec:
  selector:
    name: todo-list-app-service
  ports:
    - name: "http"
      port: 8000
      targetPort: 8000
      nodePort: 30017
    - name: "grpc"
      port: 9000
      targetPort: 9000
      nodePort: 30031
  type: NodePort