// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/billykore/todolist/internal/config"
	"github.com/billykore/todolist/internal/database/firestore"
	"github.com/billykore/todolist/internal/handler"
	"github.com/billykore/todolist/internal/pkg/log"
	"github.com/billykore/todolist/internal/repository"
	"github.com/billykore/todolist/internal/server"
	"github.com/billykore/todolist/internal/usecase"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func todoApp(cfg *config.Config) *app {
	engine := gin.Default()
	logger := log.NewLogger()
	client := firestore.New(cfg)
	todoRepository := repository.NewTodoRepository(client)
	todoUsecase := usecase.NewTodoUsecase(logger, todoRepository)
	todoHandler := handler.NewTodoHandler(todoUsecase)
	router := server.NewRouter(engine, todoHandler)
	httpServer := server.NewHTTPServer(cfg, router)
	mainApp := newApp(httpServer)
	return mainApp
}
