// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/billykore/todolist/internal/config"
	"github.com/billykore/todolist/internal/database/firestore"
	"github.com/billykore/todolist/internal/pkg/log"
	"github.com/billykore/todolist/internal/repository"
	"github.com/billykore/todolist/internal/server"
	"github.com/billykore/todolist/internal/service"
	"github.com/billykore/todolist/internal/usecase"
)

import (
	_ "github.com/joho/godotenv/autoload"
)

// Injectors from wire.go:

func todoApp(cfg *config.Config) *app {
	logger := log.NewLogger()
	authUsecase := usecase.NewAuthUsecase()
	authService := service.NewAuthService(authUsecase)
	client := firestore.New(cfg)
	todoRepository := repository.NewTodoRepository(client)
	todoUsecase := usecase.NewTodoUsecase(logger, todoRepository)
	todoService := service.NewTodoService(todoUsecase)
	httpServer := server.NewHTTPServer(logger, cfg, authService, todoService)
	grpcServer := server.NewGRPCServer(logger, cfg, authService, todoService)
	mainApp := newApp(httpServer, grpcServer)
	return mainApp
}
