apiVersion: apps/v1
kind: Deployment
metadata:
  name: monorepo-gateway
spec:
  selector:
    matchLabels:
      app: monorepo-gateway-service
  replicas: 1
  template:
    metadata:
      labels:
        app: monorepo-gateway-service
    spec:
      automountServiceAccountToken: false
      containers:
        - name: monorepo-gateway
          image: billykore/monorepo-gateway:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          command: [ "/usr/bin/krakend" ]
          args: [ "run", "-d", "-c", "/etc/krakend/gateway.json", "-p", "3000" ]
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          env:
            - name: KRAKEND_PORT
              value: "3000"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 300m
              memory: 300Mi

---

apiVersion: v1
kind: Service
metadata:
  name: monorepo-gateway-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: monorepo-gateway-service
