services:
  auth-db-postgres:
    image: postgres:alpine3.19
    container_name: auth-db-postgres
    env_file:
      - db.env
    ports:
      - "9001:5432"
    volumes:
      - auth-db-postgres-volume:/var/lib/postgresql/data
    networks:
      - backend-net

  auth-service:
    container_name: auth-service
    image: billykore/auth-service:latest
    ports:
      - "3001:8000"
    env_file:
      - service.env
    depends_on:
      - auth-db-postgres
    networks:
      - backend-net

volumes:
  auth-db-postgres-volume:
    name: auth-db-postgres-volume
    external: true

networks:
  backend-net:
    name: backend-net
    external: true
