// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/billykore/todolist/libs/config"
	"github.com/billykore/todolist/libs/database/firestore"
	"github.com/billykore/todolist/libs/pkg/log"
	"github.com/billykore/todolist/services/todo/repository"
	"github.com/billykore/todolist/services/todo/server"
	"github.com/billykore/todolist/services/todo/service"
	"github.com/billykore/todolist/services/todo/usecase"
)

import (
	_ "github.com/joho/godotenv/autoload"
)

// Injectors from wire.go:

func todoApp(cfg *config.Config) *app {
	logger := log.NewLogger()
	client := firestore.New(cfg)
	todo := repository.NewTodoRepository(client)
	todoUsecase := usecase.NewTodoUsecase(logger, todo)
	todoService := service.NewTodoService(todoUsecase)
	httpServer := server.NewHTTPServer(logger, cfg, todoService)
	grpcServer := server.NewGRPCServer(logger, cfg, todoService)
	mainApp := newApp(httpServer, grpcServer)
	return mainApp
}
