services:
  product-db-postgres:
    image: postgres:alpine3.19
    container_name: product-db-postgres
    env_file:
      - db.env
    ports:
      - "9002:5432"
    volumes:
      - product-db-postgres-volume:/var/lib/postgresql/data
    networks:
      - backend

  product-service:
    container_name: product-service
    image: billykore/product-service:latest
    ports:
      - "3002:8000"
    env_file:
      - service.env
    depends_on:
      - product-db-postgres
    networks:
      - backend

volumes:
  product-db-postgres-volume:
    name: product-db-postgres-volume
    external: true

networks:
  backend:
    name: backend-net
    external: true