// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/billykore/kore/backend/pkg/config"
	"github.com/billykore/kore/backend/pkg/db"
	"github.com/billykore/kore/backend/pkg/log"
	"github.com/billykore/kore/backend/pkg/net/rabbit"
	"github.com/billykore/kore/backend/services/shipping/internal/handler"
	"github.com/billykore/kore/backend/services/shipping/internal/repo"
	"github.com/billykore/kore/backend/services/shipping/internal/server"
	"github.com/billykore/kore/backend/services/shipping/internal/usecase"
	"github.com/labstack/echo/v4"
)

import (
	_ "github.com/joho/godotenv/autoload"
)

// Injectors from wire.go:

func shippingApp(cfg *config.Config) *app {
	logger := log.NewLogger()
	echoEcho := echo.New()
	rabbitRabbit := rabbit.New(cfg, logger)
	gormDB := db.NewPostgres(cfg)
	shippingRepo := repo.NewShippingRepository(gormDB)
	shippingUsecase := usecase.NewShippingUsecase(logger, rabbitRabbit, shippingRepo)
	shippingHandler := handler.NewShippingHandler(shippingUsecase)
	router := server.NewRouter(cfg, logger, echoEcho, shippingHandler)
	httpServer := server.NewHTTPServer(router)
	mainApp := newApp(httpServer)
	return mainApp
}
