apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-db-postgres-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-db-postgres-volume-claim
  labels:
    app: auth-db-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Mi
